name: ball-action-spotting-cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10
  
  # Core dependencies
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  
  # Computer Vision
  - opencv=4.7.0
  - pytorch-cpu
  - torchvision-cpu
  
  # Pip dependencies
  - pip
  - pip:
    - rosny==0.0.6
    - SoccerNet
    - timm==0.9.2
    - kornia==0.6.12
    - pytorch-argus==1.0.0
    - ultralytics>=8.0.0
    - lap>=0.4.0
